src/Entity/Todo.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;

use App\Repository\TodoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TodoRepository::class)
 */
class Todo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Ce champ ne peut être vide")
     * @Assert\Length(min = 15, minMessage = "Au minimum {{ limit }} caractères")
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Assert\NotBlank(message="Ce champ ne peut être vide")
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_for;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="todos")
     */
    private $category;

    /**
     * Lors de l'instance d'une Todo, on définit les dates de création et de MAJ.
     */
    function __construct()
    {
        $now = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
        $this
            ->setCreatedAt($now)
            ->setUpdatedAt($now);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDateFor(): ?\DateTimeInterface
    {
        return $this->date_for;
    }

    public function setDateFor(\DateTimeInterface $date_for): self
    {
        $this->date_for = $date_for;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Todo;
use App\Entity\Category;
use App\Form\TodoFormType;
use App\Repository\TodoRepository;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\BrowserKit\Request as BrowserKitRequest;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TodoController extends AbstractController
{

    private $categories;

    function __construct(CategoryRepository $repo)
    {
        $this->categories = $repo->findAll();        
    }



    /**
     * @Route("/todo", name="app_todo")
     */
    public function index(TodoRepository $repo): Response
    {
        $todos = $repo->findAll();
        // dd($todos);
        return $this->render('todo/index.html.twig', [
            'todos' => $todos,
            'categories' => $this->categories
        ]);
    }

        /**
     * @Route("/detail{id}", name="app_todo_detail")
     */
    public function detail($id, TodoRepository $repo): Response
    {
        $todo = $repo->find($id);
        // dd($todos);
        return $this->render('todo/detail.html.twig', [
            'todo' => $todo,
            'categories' => $this->categories
        ]);
    }

    /**
     * @Route("/todo/create", name="app_todo_create", methods= {"GET", "POST"})
     *
     * @return void
     */
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        #Etape d'affichage (GET)
        $todo = new Todo;
        $form = $this->createForm(TodoFormType::class, $todo);

        #Etape soumission (POST)
        $form->handleRequest($request);
        if($form->isSubmitted()&& $form->isValid()){
            //Méthode que l'on trouve dans des anciennes ressources :
            // $this->getDoctrine()->getManager()->persist($todo);
            $em -> persist($todo);
            $em -> flush();
            return $this->redirectToRoute('app_todo');
        }
        return $this->render('todo/create.html.twig', 
            ['formTodo' => $form->createView(),
            'categories' => $this->categories]);
    }

    /**
     * paramconverter => correspondance entre un id dans la route et un objet du type Todo
     * @Route("/detail{id}/update", name="app_todo_update", methods= {"GET", "POST"})
     */
    public function update(Todo $todo, Request $request, EntityManagerInterface $em): Response
    {
        // dd($todo);
        $form = $this->createForm(TodoFormType::class, $todo);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            # Update
            $todo->setUpdatedAt(new \DateTime('now'));
            $em->flush();
            # Création d'un message Flash (session flash)
            $this->addFlash(
                'info',
                'Modification enregistrée avec succès !'
            );
            # On revient sur la même page (methode GET)
            return $this->redirectToRoute('app_todo_update', ['id' => $todo->getId()]);
        }
        return $this->render('todo/update.html.twig', 
            ['formTodo' => $form->createView(),
            'todo' => $todo,
            'categories' => $this->categories]);
    }

    /**
     * @Route("/todo/{id}/delete", name="app_todo_delete")
     *
     * @param Todo $todo
     * @param EntityManagerInterface $em
     * @return void
     */
    public function delete(Todo $todo, EntityManagerInterface $em){
        $em->remove($todo);
        $em->flush();
        return $this->redirectToRoute('app_todo');
    }

    /**
     * @Route("/todo/{id}/deletecsrf", name="app_todo_delete_csrf", methods={"DELETE"})
     *
     * @param Todo $todo
     * @param EntityManagerInterface $em
     * @return void
     * 
     * $request->request->get()  :  POST
     * $request->query->get()    :  GET
     */
    public function delete2(Todo $todo, EntityManagerInterface $em, Request $request){
        $submittedToken = $request->request->get('token');
        // dd($submittedToken);
        if($this->isCsrfTokenValid('delete-item', $submittedToken)){
            $em->remove($todo);
            $em->flush();
        }
        
        return $this->redirectToRoute('app_todo');
    }

    /**
     * @Route("/todo/category/{id}", name="app_todo_category")
     *
     * @param Category $cat
     * @return void
     */
    public function todoByCategory(Category $cat): Response{
        return $this->render('todo/index.html.twig', [
            'todos' => $cat->getTodos(),
            'categories' => $this->categories
        ]);
    }

}

templates/todo/create.html.twig
{% extends "base.html.twig" %}

{% block body %}

<div class="container">


    <div class="row justify-content-center">

        <h3 class="my-5">Créer une nouvelle Todo</h3>

        <div class="col-6">
            {{ form( formTodo ) }}
        </div>

    </div>
</div>

{% endblock %}

templates/todo/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello in Todo !{% endblock %}

{% block body %}


        <div class="container"> 
            <ul>
                <li> {{ todo.title }} </li>
                <li> Catégorie : {{ todo.category.name }} </li>
                <br>
                <li> Créée le {{ todo.createdAt|date('d/m/Y') }} </li>
                <li> Modifiée le {{ todo.updatedAt|date('d/m/Y') }} </li>
                <li> Pour le : {{ todo.dateFor|date('d/m/Y') }} </li>
            </ul>

            <hr>
            
            <a href=" {{ path('app_todo') }}" class=" btn btn-success"> Accueil </a>

        </div>

{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TodoController!{% endblock %}

{% block body %}

    <div class="container">
        <a href="{{ path('app_todo_create') }}" class="btn my-5 btn-outline-danger">Nouvelle ToDo</a>
    </div>
    
    {% for todo in todos %}
 
        <div class="container">
            <table class="table table-dark table-striped">
            <thead>
                <tr>
                <th scope="col">Titre</th>
                <th scope="col">Catégorie</th>
                <th scope="col">Crée le</th>
                <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <th scope="row">
                    {{ todo.title }}
                </th>
                <td>{{ todo.category.name }}</td>
                <td>{{ todo.createdAt|date('d/m/Y') }}</td>
                <td> 
                    <a href="{{ path('app_todo_detail', {'id' : todo.id})}}"class="btn btn-outline-info">Voir</a>
                    <a href="{{ path('app_todo_update', {'id' : todo.id})}}"class="btn btn-outline-warning">Editer</a>                  
                </td>
                <td>
                    <a href="{{ path('app_todo_delete', {'id' : todo.id})}}"class="btn btn-danger">Supprimer</a>                  
                </td>
                </tr>
    
            </tbody>
            </table>
        </div>
                    
        {% endfor %}
{% endblock %}

templates/todo/update.html.twig
{% extends "base.html.twig" %}

{% block body %}

<div class="container">


    <div class="column justify-content-center">

        <h3 class="my-5">Modifier la Todo</h3>

        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="alert alert-{{ label }} my-3">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}
    
            {{ form( formTodo ) }}
            
            <form class="deleteform" action="{{ path('app_todo_delete_csrf', { id: todo.id }) }}", method="post">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="token" value="{{ csrf_token('delete-item') }}"/>
                <button type="submit" class="btn btn-danger">Supprimer</button>
            </form>
    </div>
</div>

{% endblock %}

{% block javascripts %}

<script>

    const deleteform = document.querySelector('.deleteform');
    deleteform.addEventListener('click', function(e){
        e.preventDefault();
        if(confirm("Voulez-vous supprimer cette Todo ?")){
            this.submit()
        }
    });

</script>

{% endblock %}